// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iseaskggtqujanhgfxmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZWFza2dndHF1amFuaGdmeG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzE0ODYsImV4cCI6MjA2NTI0NzQ4Nn0.xUbNlMd76xzM8eynE-SHBlJt1xUYIL_0bErLSNIdFO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);